# Copyright 2026 NXP
# SPDX-License-Identifier: BSD-3-Clause

if(SB_CONFIG_TSN_MULTICORE_BUILD)
  if("${SB_CONFIG_SECONDARY_BOARD}" STREQUAL "")
    message(FATAL_ERROR
    "Target ${BOARD}${BOARD_QUALIFIERS} not supported for this sample. "
    "There is no remote board selected in Kconfig.sysbuild")
  endif()

  set(SECONDARY_DIR secondary)
  set(SECONDARY_APP tsn_app_secondary)

  ExternalZephyrProject_Add(
      APPLICATION ${SECONDARY_APP}
      SOURCE_DIR  ${APP_DIR}/${SECONDARY_DIR}
      BOARD       ${SB_CONFIG_SECONDARY_BOARD}
      BOARD_REVISION ${BOARD_REVISION}
  )

  # Primary core application is dependent on
  # 'zephyr_image_info.h' generated by remote application,
  # unless the secondary core boots from flash,
  # in that case the primary core doesn't depend on it.
  add_dependencies(${DEFAULT_IMAGE} ${SECONDARY_APP})
  sysbuild_add_dependencies(CONFIGURE ${DEFAULT_IMAGE} ${SECONDARY_APP})

  if(SB_CONFIG_BOOT_SECONDARY_FROM_FLASH)
    set_config_bool(${DEFAULT_IMAGE} CONFIG_CM7_BOOT_FROM_FLASH y)
    set_config_bool(${SECONDARY_APP} CONFIG_CM7_BOOT_FROM_FLASH y)

    if("${BOARD}" STREQUAL "mimxrt1180_evk")
      set(${SECONDARY_APP}_EXTRA_DTC_OVERLAY_FILE
        "${ZEPHYR_BASE}/boards/nxp/mimxrt1180_evk/cm7_flash_boot.overlay"
        CACHE INTERNAL ""
      )
    endif()
  else()
    if("${BOARD}" STREQUAL "mimxrt1180_evk")
      set(${SECONDARY_APP}_EXTRA_DTC_OVERLAY_FILE
        "${ZEPHYR_BASE}/boards/nxp/mimxrt1180_evk/cm7_code_hyperram.overlay"
        CACHE INTERNAL ""
      )
    endif()
  endif()

  set(${DEFAULT_IMAGE}_EXTRA_CONF_FILE
    "${APP_DIR}/overlay-primary-core.conf"
    CACHE INTERNAL ""
  )
  set(${DEFAULT_IMAGE}_EXTRA_DTC_OVERLAY_FILE
    "${APP_DIR}/../../common/overlays/nxp_rt118x_cm33_multicore.overlay"
    CACHE INTERNAL ""
  )
endif()
