# Copyright 2026 NXP
# SPDX-License-Identifier: BSD-3-Clause

if(SB_CONFIG_TSN_MULTICORE_BUILD)
  if("${SB_CONFIG_SECONDARY_BOARD}" STREQUAL "")
    message(FATAL_ERROR
    "Target ${BOARD}${BOARD_QUALIFIERS} not supported for this sample. "
    "There is no remote board selected in Kconfig.sysbuild")
  endif()

  set(SECONDARY_DIR secondary)
  set(SECONDARY_APP tsn_app_secondary)

  ExternalZephyrProject_Add(
      APPLICATION ${SECONDARY_APP}
      SOURCE_DIR  ${APP_DIR}/${SECONDARY_DIR}
      BOARD       ${SB_CONFIG_SECONDARY_BOARD}
      BOARD_REVISION ${BOARD_REVISION}
  )

  # Primary core application is dependent on
  # 'zephyr_image_info.h' generated by remote application,
  # unless the secondary core boots from flash,
  # in that case the primary core doesn't depend on it.
  # Build the remote application first anyway for the first case.
  add_dependencies(${DEFAULT_IMAGE} ${SECONDARY_APP})

  set(${DEFAULT_IMAGE}_EXTRA_CONF_FILE
    "${APP_DIR}/overlay-primary-core.conf"
    CACHE INTERNAL ""
  )
  set(${DEFAULT_IMAGE}_EXTRA_DTC_OVERLAY_FILE
    "${APP_DIR}/../../common/overlays/nxp_rt118x_cm33_multicore.overlay"
    CACHE INTERNAL ""
  )
endif()
