CONFIG_PICOLIBC_USE_MODULE=y

CONFIG_FPU=y

CONFIG_CODE_DATA_RELOCATION=y

CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=512
CONFIG_ISR_STACK_SIZE=2048
CONFIG_IDLE_STACK_SIZE=320

CONFIG_THREAD_NAME=y

CONFIG_SRAM_VECTOR_TABLE=y
CONFIG_ARM_VECTOR_TABLE_ITCM=y
CONFIG_SRAM_SW_ISR_TABLE=y

CONFIG_NOCACHE_MEMORY=y

CONFIG_GPIO=n
CONFIG_CORTEX_M_SYSTICK_INTERRUPT_PRIORITY=5

CONFIG_MCUX_OPTIMIZED_MEMCPY=y
CONFIG_MCUX_OPTIMIZED_MEMSET=y
