CONFIG_PICOLIBC_USE_MODULE=y

CONFIG_FPU=y

CONFIG_CODE_DATA_RELOCATION=y
CONFIG_CODE_DATA_RELOCATION_SRAM=y

CONFIG_SIZE_OPTIMIZATIONS=y

CONFIG_MEMC_MCUX_FLEXSPI_INIT_XIP=y
CONFIG_FLASH=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=1024
CONFIG_ISR_STACK_SIZE=1024
CONFIG_IDLE_STACK_SIZE=256

CONFIG_THREAD_NAME=y

CONFIG_SRAM_VECTOR_TABLE=y
CONFIG_SRAM_SW_ISR_TABLE=y

CONFIG_GPIO=n
CONFIG_CORTEX_M_SYSTICK_INTERRUPT_PRIORITY=5

CONFIG_ZVFS_POLL_MAX=10
