CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y

CONFIG_FILE_SYSTEM_LITTLEFS=y
CONFIG_FLASH_MAP=y

# Error messages are handled by the application
CONFIG_FS_LOG_LEVEL_OFF=y

# At first boot, automount fs format is using the
# main stack, which requires a bigger stack size
CONFIG_MAIN_STACK_SIZE=2048
