# Core networking
CONFIG_NETWORKING=y
CONFIG_NET_LOG=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV4_IGMP=n
CONFIG_NET_DHCPV4=y
CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_STATISTICS=y
CONFIG_NET_STATISTICS_USER_API=y

CONFIG_NET_IPV4_MTU=1460

# Ethernet and socket support
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_ETHERNET_RESERVE_HEADER=y
CONFIG_NET_SOCKETS=y

# Network buffers and contexts
CONFIG_NET_BUF_FIXED_DATA_SIZE=n
CONFIG_NET_BUF_VARIABLE_DATA_SIZE=y
CONFIG_NET_BUF_POOL_USAGE=y

CONFIG_NET_PKT_BUF_RX_DATA_POOL_SIZE=8192
CONFIG_NET_PKT_BUF_TX_DATA_POOL_SIZE=8192
CONFIG_NET_PKT_LOG_LEVEL_OFF=y

CONFIG_NET_TCP_LOG_LEVEL_OFF=y
CONFIG_NET_TCP_WORKER_PRIO=7

CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=1
CONFIG_NET_MAX_CONTEXTS=4
CONFIG_NET_MAX_CONN=4

CONFIG_NET_TX_STACK_SIZE=1024
CONFIG_NET_RX_STACK_SIZE=1536
CONFIG_NET_TCP_WORKQ_STACK_SIZE=768
CONFIG_NET_MGMT_EVENT_STACK_SIZE=256
CONFIG_NET_SOCKETS_SERVICE_STACK_SIZE=1024

# Traffic classes
CONFIG_NET_TC_TX_COUNT=0
CONFIG_NET_TC_RX_COUNT=2

# zperf
CONFIG_NET_ZPERF=y
CONFIG_NET_ZPERF_SERVER=y
CONFIG_ZPERF_WORK_Q_THREAD_PRIORITY=7
CONFIG_NET_ZPERF_LOG_LEVEL_OFF=y
CONFIG_NET_ZPERF_MAX_PACKET_SIZE=2920
CONFIG_NET_ZPERF_MAX_SESSIONS=2

# Test random generator
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_NET_IPV6=n
