# Copyright 2026 NXP
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_SHELL=y
CONFIG_SHELL_MINIMAL=y

CONFIG_NET_SHELL=y
CONFIG_NET_SHELL_SHOW_DISABLED_COMMANDS=n

# Allow '-h' command option
CONFIG_SHELL_HELP_OPT_PARSE=n
CONFIG_SHELL_DEFAULT_TERMINAL_WIDTH=100
CONFIG_SHELL_GETOPT=y

CONFIG_SHELL_METAKEYS=y
CONFIG_SHELL_HELP=y
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_HISTORY_BUFFER=256

CONFIG_SHELL_STACK_SIZE=5120
