CONFIG_EVENTS=y
CONFIG_DYNAMIC_INTERRUPTS=y

# RTOS Abstraction Layer dependencies
CONFIG_SCHED_CPU_MASK=y

CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y

CONFIG_NOCACHE_MEMORY=y

CONFIG_NET_IF_MAX_IPV4_COUNT=2
