CONFIG_ASSERT=y

CONFIG_FPU=y

# Use NEWLIB for ARM GNU Toolchain
CONFIG_NEWLIB_LIBC=y

# Logging subsystem
CONFIG_LOG=y
CONFIG_LOG_PRINTK=y

CONFIG_EVENTS=y
CONFIG_DYNAMIC_INTERRUPTS=y

# RTOS Abstraction Layer dependencies
CONFIG_SCHED_CPU_MASK=y

CONFIG_DYNAMIC_THREAD=y
CONFIG_DYNAMIC_THREAD_ALLOC=y

CONFIG_SIZE_OPTIMIZATIONS=y